name: Test Lambda deployment changes
on:
  push:
    branches-ignore:
      - master
    paths:
      - 'lambda/**'
      - 'terraform/lambda.tf'
      - 'modules/lambda_function/**'
      - '.github/workflows/build_docker_image.yaml'
  workflow_dispatch:
      
jobs:
  lambda-deployment-changes:

    name: Terraform changes
    runs-on: ubuntu-latest
    
    env:
      working-directory: './terraform'

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2.3.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.LD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.LD_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14
          
      #terraform init
      - name: 'Terraform Init'
        run: terraform init
        working-directory: ${{ env.working-directory }}

      #terraform format
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      #terraform validate
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ${{ env.working-directory }}

      #terraform plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ${{ env.working-directory }}

      #terraform apply
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-appove
        working-directory: ${{ env.working-directory }}

      
